#!/bin/bash
# ClaudeOS Issue自動生成スクリプト
# Usage: ./create-issue.sh "<TITLE>" "<BODY>" [LABELS]
# 自動生成トリガー: TODO検出、FIXME検出、CI失敗、テスト不足

set -euo pipefail

TITLE="${1:?Usage: $0 <TITLE> <BODY> [LABELS]}"
BODY="${2:?Usage: $0 <TITLE> <BODY> [LABELS]}"
LABELS="${3:-auto-generated}"

echo "[ClaudeOS] Issue作成: $TITLE"

# ラベルの存在確認・作成
for LABEL in $(echo "$LABELS" | tr ',' ' '); do
  gh label create "$LABEL" --description "Auto-generated by ClaudeOS" --color "0E8A16" 2>/dev/null || true
done

# Issue作成
ISSUE_URL=$(gh issue create \
  --title "$TITLE" \
  --body "$BODY" \
  --label "$LABELS")

echo "[ClaudeOS] Issue作成完了: $ISSUE_URL"
echo "$ISSUE_URL"
