#!/bin/bash
# ClaudeOS PR自動生成スクリプト
# Usage: ./create-pr.sh [TITLE] [BODY]

set -euo pipefail

BRANCH=$(git branch --show-current)
BASE_BRANCH="${BASE_BRANCH:-main}"

if [ "$BRANCH" = "$BASE_BRANCH" ]; then
  echo "[ClaudeOS] Error: mainブランチから直接PRは作成できません"
  exit 1
fi

TITLE="${1:-Auto PR: $BRANCH}"
BODY="${2:-## Summary
Auto-generated by ClaudeOS

## Changes
- Implementation updates on branch: $BRANCH

## Test Results
- Pending CI verification

## Checklist
- [ ] Tests pass
- [ ] Lint clean
- [ ] Build succeeds
- [ ] Documentation updated
}"

echo "[ClaudeOS] PR作成: $TITLE (${BRANCH} → ${BASE_BRANCH})"

# リモートにブランチをプッシュ
git push -u origin "$BRANCH" 2>/dev/null || true

# PR作成
PR_URL=$(gh pr create \
  --title "$TITLE" \
  --body "$BODY" \
  --base "$BASE_BRANCH" \
  --head "$BRANCH")

echo "[ClaudeOS] PR作成完了: $PR_URL"
echo "$PR_URL"
